# Generated by Django 5.1 on 2024-08-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_postimage_post_delete_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='postTitle',
            field=models.CharField(default='', max_length=100, verbose_name='포스트 제목'),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='작성날짜'),
        ),
    ]
