# Generated by Django 5.1 on 2024-08-29 19:25

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_content_alter_post_posttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[utils.validators.validate_post_content], verbose_name='포스트 내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postTitle',
            field=models.CharField(max_length=50, validators=[utils.validators.validate_post_title], verbose_name='포스트 제목'),
        ),
    ]
